<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $title }}</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #009639; padding-bottom: 10px; }
        .header img { height: 60px; width: auto; vertical-align: middle; margin-right: 10px; }
        .header h1 { margin: 0; color: #009639; font-size: 18px; line-height: 1.2; }
        .header p { margin: 0; color: #666; font-size: 11px; }
        
        .meta { margin-bottom: 20px; font-size: 11px; color: #555; overflow: hidden; }
        .meta-left { float: left; }
        .meta-right { float: right; text-align: right; }

        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 6px; text-align: left; font-size: 11px; }
        th { background-color: #f2f2f2; font-weight: bold; color: #333; }
        tr:nth-child(even) { background-color: #fafafa; }

        .footer { position: fixed; bottom: 0; left: 0; right: 0; font-size: 10px; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 5px; }
    </style>
</head>
<body>
    <div class="header">
        <img src="{{ public_path('images/CLSU_LOGO.png') }}" alt="CLSU Logo">
        <h1>{{ $title }}</h1>
        <p>Procurement Management Office - Central Luzon State University</p>
    </div>

    <div class="meta">
        <div class="meta-left">
            <strong>Generated By:</strong> {{ Auth::user()->name ?? 'System Admin' }}
        </div>
        <div class="meta-right">
            <strong>Date:</strong> {{ now()->format('F d, Y h:i A') }}
        </div>
    </div>

    @if($type === 'procurement')
        <table>
            <thead>
                <tr>
                    <th>Request Title</th>
                    <th>PR Number</th>
                    <th>Status</th>
                    <th>Quantity</th>
                    <th>Estimated Cost</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $item)
                <tr>
                    <td>{{ $item->name }}</td>
                    <td>{{ $item->code }}</td>
                    <td>{{ ucfirst($item->status) }}</td>
                    <td>{{ $item->rooms }}</td>
                    <td>{{ $item->total_area }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @elseif($type === 'suppliers')
        <table>
            <thead>
                <tr>
                    <th>Supplier/Item Name</th>
                    <th>Reference No.</th>
                    <th>Category</th>
                    <th>Status</th>
                    <th>Condition</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $item)
                <tr>
                    <td>{{ $item->name }}</td>
                    <td>{{ $item->serial_number }}</td>
                    <td>{{ $item->category }}</td>
                    <td>{{ ucfirst(str_replace('_', ' ', $item->status)) }}</td>
                    <td>{{ ucfirst(str_replace('_', ' ', $item->condition)) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @elseif($type === 'orders')
        <table>
            <thead>
                <tr>
                    <th>Order ID</th>
                    <th>Item Description</th>
                    <th>Supplier</th>
                    <th>Priority</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $item)
                <tr>
                    <td>{{ $item->request_id }}</td>
                    <td>{{ $item->issue }}</td>
                    <td>{{ $item->location }}</td>
                    <td>{{ ucfirst($item->priority) }}</td>
                    <td>{{ ucfirst($item->status) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div style="text-align: center; padding: 50px; color: #777;">
            <p>No data template available for this report type.</p>
        </div>
    @endif

    <div class="footer">
        Generated via CLSU PMO System | Page <span class="page-number"></span>
    </div>

    <script type="text/php">
        if (isset($pdf)) {
            $pdf->page_script('
                $font = $fontMetrics->get_font("sans-serif", "normal");
                $pdf->text(520, 820, "Page " . $PAGE_NUM . " of " . $PAGE_COUNT, $font, 9);
            ');
        }
    </script>
</body>
</html>
