@extends('admin.pmo-layout')

@section('title', 'Reports')
@section('crumb', 'Reports')

@section('content')
<div class="d-flex justify-content-between align-items-start mb-3">
  <div class="d-flex align-items-center gap-3">
    <img src="/images/clsu-logo-green.png" alt="CLSU Seal" style="width:56px;height:56px;border-radius:14px;background:#fff;border:2px solid var(--clsu-green);object-fit:contain;">
    <div>
      <h1 class="h3 fw-bold mb-1">PMO Reports</h1>
      <div class="text-muted">Generate and view PMO Reports</div>
    </div>
  </div>
  <button class="btn text-white rounded-4" style="background: var(--clsu-green);" data-bs-toggle="modal" data-bs-target="#generateReportModal">
    <svg width="18" height="18" fill="currentColor" viewBox="0 0 24 24" class="me-2"><path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z"/></svg>
    Generate Report
  </button>
</div>

<!-- Quick Report Cards -->
<div class="row g-3">
  <div class="col-md-4">
    <div class="card rounded-4 h-100">
      <div class="card-body">
        <div class="d-flex align-items-center mb-2">
          <svg width="24" height="24" fill="var(--clsu-green)" viewBox="0 0 24 24" class="me-2">
            <path d="M12 7V3H2v18h20V7H12zM6 19H4v-2h2v2zm0-4H4v-2h2v2zm0-4H4V9h2v2zm0-4H4V5h2v2zm4 12H8v-2h2v2zm0-4H8v-2h2v2zm0-4H8V9h2v2zm0-4H8V5h2v2zm10 12h-8v-2h2v-2h-2v-2h2v-2h-2V9h8v10zm-2-8h-2v2h2v-2zm0 4h-2v2h2v-2z"/>
          </svg>
          <h5 class="card-title mb-0 fw-bold">Purchase Request Report</h5>
        </div>
        <p class="text-muted small">Summary of all purchase requests, approvals, and procurement status</p>
        <button class="btn btn-sm rounded-3 text-white btn-download-card" style="background: var(--clsu-green);" data-report="Purchase Request Report">
          <svg width="14" height="14" fill="currentColor" viewBox="0 0 24 24" class="me-1"><path d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z"/></svg>
          Download PDF
        </button>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card rounded-4 h-100">
      <div class="card-body">
        <div class="d-flex align-items-center mb-2">
          <svg width="24" height="24" fill="var(--clsu-gold)" viewBox="0 0 24 24" class="me-2">
            <path d="M20 2H4c-1.1 0-2 .9-2 2v16c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zM8 20H4v-4h4v4zm0-6H4v-4h4v4zm0-6H4V4h4v4zm6 12h-4v-4h4v4zm0-6h-4v-4h4v4zm0-6h-4V4h4v4zm6 12h-4v-4h4v4zm0-6h-4v-4h4v4zm0-6h-4V4h4v4z"/>
          </svg>
          <h5 class="card-title mb-0 fw-bold">Supplier Directory</h5>
        </div>
        <p class="text-muted small">Complete supplier directory with accreditation and performance status</p>
        <button class="btn btn-sm rounded-3 text-white btn-download-card" style="background: var(--clsu-gold);" data-report="Supplier Directory">
          <svg width="14" height="14" fill="currentColor" viewBox="0 0 24 24" class="me-1"><path d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z"/></svg>
          Download PDF
        </button>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card rounded-4 h-100">
      <div class="card-body">
        <div class="d-flex align-items-center mb-2">
          <svg width="24" height="24" fill="#6c757d" viewBox="0 0 24 24" class="me-2">
            <path d="M22.7 19l-9.1-9.1c.9-2.3.4-5-1.5-6.9-2-2-5-2.4-7.4-1.3L9 6 6 9 1.6 4.7C.4 7.1.9 10.1 2.9 12.1c1.9 1.9 4.6 2.4 6.9 1.5l9.1 9.1c.4.4 1 .4 1.4 0l2.3-2.3c.5-.4.5-1.1.1-1.4z"/>
          </svg>
          <h5 class="card-title mb-0 fw-bold">Procurement Summary</h5>
        </div>
        <p class="text-muted small">Monthly procurement activities, order tracking, and budget utilization</p>
        <button class="btn btn-sm rounded-3 btn-download-card" style="color: var(--clsu-green); border-color: var(--clsu-green);" data-report="Procurement Summary">
          <svg width="14" height="14" fill="currentColor" viewBox="0 0 24 24" class="me-1"><path d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z"/></svg>
          Download PDF
        </button>
      </div>
    </div>
  </div>
</div>

<!-- Recent Reports Table -->
<div class="card mt-3 rounded-4">
  <div class="card-body">
    <h5 class="card-title mb-3 fw-bold">Recent Reports</h5>
    <div class="table-responsive">
      <table class="table table-hover mb-0">
        <thead class="bg-light">
          <tr>
            <th class="py-3">Report Name</th>
            <th class="py-3">Type</th>
            <th class="py-3">Generated Date</th>
            <th class="py-3">Generated By</th>
            <th class="py-3 text-end">Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="py-3 fw-semibold">Monthly Purchase Requests - January 2026</td>
            <td class="py-3"><span class="badge" style="background: var(--clsu-green);">Procurement</span></td>
            <td class="py-3">Feb 1, 2026</td>
            <td class="py-3">PMO Admin</td>
            <td class="py-3 text-end">
              <div class="btn-group btn-group-sm">
                <button class="btn btn-sm btn-view-report" style="color: var(--clsu-green); border-color: var(--clsu-green);"
                  data-name="Monthly Purchase Requests - January 2026"
                  data-type="Procurement" data-date="Feb 1, 2026" data-by="PMO Admin"
                  data-period="January 1 - 31, 2026"
                  data-summary="48 purchase requests processed. 36 approved, 8 pending, 4 returned. Total procurement value: ₱2.4M."
                  data-highlights="Bulk office supplies procurement completed. Laboratory equipment PO awarded. IT infrastructure upgrade bid ongoing.">View</button>
                <button class="btn btn-sm btn-download-report text-white" style="background: var(--clsu-gold);"
                  data-name="Monthly Purchase Requests - January 2026">Download</button>
                <button class="btn btn-sm btn-delete-report" style="color: #dc3545; border-color: #dc3545;"
                  data-name="Monthly Purchase Requests - January 2026">Delete</button>
              </div>
            </td>
          </tr>
          <tr>
            <td class="py-3 fw-semibold">Supplier Directory - Q4 2025</td>
            <td class="py-3"><span class="badge bg-info">Suppliers</span></td>
            <td class="py-3">Jan 15, 2026</td>
            <td class="py-3">PMO Admin</td>
            <td class="py-3 text-end">
              <div class="btn-group btn-group-sm">
                <button class="btn btn-sm btn-view-report" style="color: var(--clsu-green); border-color: var(--clsu-green);"
                  data-name="Supplier Directory - Q4 2025"
                  data-type="Suppliers" data-date="Jan 15, 2026" data-by="PMO Admin"
                  data-period="October - December 2025"
                  data-summary="87 registered suppliers. 72 active, 10 under review, 5 blacklisted. 12 new accreditations during the quarter."
                  data-highlights="Annual supplier performance review completed. 3 new IT suppliers accredited. Updated terms with office supply vendors.">View</button>
                <button class="btn btn-sm btn-download-report text-white" style="background: var(--clsu-gold);"
                  data-name="Supplier Directory - Q4 2025">Download</button>
                <button class="btn btn-sm btn-delete-report" style="color: #dc3545; border-color: #dc3545;"
                  data-name="Supplier Directory - Q4 2025">Delete</button>
              </div>
            </td>
          </tr>
          <tr>
            <td class="py-3 fw-semibold">Procurement Summary - December 2025</td>
            <td class="py-3"><span class="badge" style="background: var(--clsu-gold);">Orders</span></td>
            <td class="py-3">Jan 5, 2026</td>
            <td class="py-3">PMO Admin</td>
            <td class="py-3 text-end">
              <div class="btn-group btn-group-sm">
                <button class="btn btn-sm btn-view-report" style="color: var(--clsu-green); border-color: var(--clsu-green);"
                  data-name="Procurement Summary - December 2025"
                  data-type="Orders" data-date="Jan 5, 2026" data-by="PMO Admin"
                  data-period="December 1 - 31, 2025"
                  data-summary="38 purchase orders processed. 30 delivered, 5 in transit, 3 pending. Total order value: ₱1.8M."
                  data-highlights="Year-end procurement close-out completed. Emergency supply order for College of Engineering. Annual supplier contract renewals finalized.">View</button>
                <button class="btn btn-sm btn-download-report text-white" style="background: var(--clsu-gold);"
                  data-name="Procurement Summary - December 2025">Download</button>
                <button class="btn btn-sm btn-delete-report" style="color: #dc3545; border-color: #dc3545;"
                  data-name="Procurement Summary - December 2025">Delete</button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- View Report Modal -->
<div class="modal fade" id="viewReportModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content rounded-4 border-0 shadow">
      <div class="modal-header border-0 pb-0">
        <h5 class="modal-title fw-bold">Report Preview</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body p-4">
        <div class="row g-3">
          <div class="col-12">
            <h4 class="fw-bold mb-0" id="rptName"></h4>
          </div>
          <div class="col-md-4">
            <label class="form-label text-muted small">Type</label>
            <div><span id="rptType" class="badge" style="background: var(--clsu-green);"></span></div>
          </div>
          <div class="col-md-4">
            <label class="form-label text-muted small">Generated</label>
            <div class="fw-semibold" id="rptDate"></div>
          </div>
          <div class="col-md-4">
            <label class="form-label text-muted small">Generated By</label>
            <div class="fw-semibold" id="rptBy"></div>
          </div>
          <div class="col-12">
            <label class="form-label text-muted small">Period Covered</label>
            <div class="fw-semibold" id="rptPeriod"></div>
          </div>
          <div class="col-12">
            <label class="form-label text-muted small">Summary</label>
            <div class="p-3 bg-light rounded-3" id="rptSummary"></div>
          </div>
          <div class="col-12">
            <label class="form-label text-muted small">Highlights</label>
            <div class="p-3 bg-light rounded-3" id="rptHighlights"></div>
          </div>
        </div>
      </div>
      <div class="modal-footer border-0 pt-0">
        <button type="button" class="btn rounded-3" style="color: var(--clsu-green); border-color: var(--clsu-green);" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn rounded-3 text-white" style="background: var(--clsu-gold);" id="rptDownloadBtn">Download PDF</button>
      </div>
    </div>
  </div>
</div>

<!-- Generate Report Modal -->
<div class="modal fade" id="generateReportModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content rounded-4 border-0 shadow">
      <div class="modal-header border-0 pb-0">
        <h5 class="modal-title fw-bold">Generate New Report</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body p-4">
        <form id="generateReportForm">
          <div class="mb-3">
            <label class="form-label fw-bold">Report Type <span class="text-danger">*</span></label>
            <select class="form-select rounded-3" id="genType" required>
              <option value="">Select type</option>
              <option value="procurement">Purchase Request Report</option>
              <option value="suppliers">Supplier Directory</option>
              <option value="orders">Procurement Summary</option>
              <option value="bids">Bid Analysis Report</option>
              <option value="custom">Custom Report</option>
            </select>
          </div>
          <div class="row g-3 mb-3">
            <div class="col-6">
              <label class="form-label fw-bold">From Date</label>
              <input type="date" class="form-control rounded-3" id="genFrom">
            </div>
            <div class="col-6">
              <label class="form-label fw-bold">To Date</label>
              <input type="date" class="form-control rounded-3" id="genTo">
            </div>
          </div>
          <div class="mb-3">
            <label class="form-label fw-bold">Format</label>
            <select class="form-select rounded-3" id="genFormat">
              <option value="pdf">PDF</option>
              <option value="excel">Excel (XLSX)</option>
              <option value="csv">CSV</option>
            </select>
          </div>
          <div class="mb-3">
            <label class="form-label fw-bold">Notes</label>
            <textarea class="form-control rounded-3" id="genNotes" rows="2" placeholder="Additional instructions..."></textarea>
          </div>
          <div class="d-flex gap-2 justify-content-end mt-4">
            <button type="button" class="btn rounded-4 px-4" style="color: var(--clsu-gold); border-color: var(--clsu-gold);" data-bs-dismiss="modal">Cancel</button>
            <button type="submit" class="btn rounded-4 px-4 text-white" style="background: var(--clsu-green);">Generate Report</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Delete Report Modal -->
<div class="modal fade" id="deleteReportModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content rounded-4 border-0 shadow">
      <div class="modal-header border-0 pb-0">
        <h5 class="modal-title fw-bold">Delete Report</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body p-4">
        <div class="text-center mb-3">
          <svg width="48" height="48" fill="#dc3545" viewBox="0 0 24 24">
            <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z"/>
          </svg>
        </div>
        <p class="text-center mb-1">Are you sure you want to delete this report?</p>
        <p class="text-center fw-bold" id="deleteRptName"></p>
        <p class="text-center text-muted small">This action cannot be undone.</p>
      </div>
      <div class="modal-footer border-0 pt-0 justify-content-center">
        <button type="button" class="btn rounded-3 px-4" style="color: var(--clsu-green); border-color: var(--clsu-green);" data-bs-dismiss="modal">Cancel</button>
        <button type="button" class="btn rounded-3 px-4 text-white" style="background: #dc3545;" id="confirmDeleteRpt">Delete Report</button>
      </div>
    </div>
  </div>
</div>

@endsection

@section('scripts')
<script>
// View Report
document.querySelectorAll('.btn-view-report').forEach(btn => {
  btn.addEventListener('click', function() {
    document.getElementById('rptName').textContent = this.dataset.name;
    document.getElementById('rptType').textContent = this.dataset.type;
    document.getElementById('rptDate').textContent = this.dataset.date;
    document.getElementById('rptBy').textContent = this.dataset.by;
    document.getElementById('rptPeriod').textContent = this.dataset.period;
    document.getElementById('rptSummary').textContent = this.dataset.summary;
    document.getElementById('rptHighlights').textContent = this.dataset.highlights;

    // Download button in modal
    document.getElementById('rptDownloadBtn').onclick = function() {
      alert(`Generating and downloading "${btn.dataset.name}" report...`);
      const reportName = btn.dataset.name; // Use existing dataset name
      // Extract type from name potentially, or pass type in dataset. For now pass name as type for basic matching
      window.location.href = `{{ route('pmo.reports.download') }}?type=${encodeURIComponent(reportName)}`;
    };

    new bootstrap.Modal(document.getElementById('viewReportModal')).show();
  });
});

// Download Report
document.querySelectorAll('.btn-download-report').forEach(btn => {
  btn.addEventListener('click', function() {
    alert(`Generating and downloading "${this.dataset.name}" report...`);
    const reportName = this.dataset.name;
    window.location.href = `{{ route('pmo.reports.download') }}?type=${encodeURIComponent(reportName)}`;
  });
});

// Quick Download from Cards
document.querySelectorAll('.btn-download-card').forEach(btn => {
  btn.addEventListener('click', function() {
    alert(`Generating and downloading "${this.dataset.report}" report...`);
    const reportType = this.dataset.report;
    window.location.href = `{{ route('pmo.reports.download') }}?type=${encodeURIComponent(reportType)}`;
  });
});

// Delete Report
let deleteRptRow = null;
document.querySelectorAll('.btn-delete-report').forEach(btn => {
  btn.addEventListener('click', function() {
    deleteRptRow = this.closest('tr');
    document.getElementById('deleteRptName').textContent = this.dataset.name;
    new bootstrap.Modal(document.getElementById('deleteReportModal')).show();
  });
});

document.getElementById('confirmDeleteRpt').addEventListener('click', function() {
  if (deleteRptRow) {
    const name = document.getElementById('deleteRptName').textContent;
    deleteRptRow.remove();
    bootstrap.Modal.getInstance(document.getElementById('deleteReportModal')).hide();
    alert(`"${name}" has been deleted.`);
    deleteRptRow = null;
  }
});

// Generate Report
document.getElementById('generateReportForm').addEventListener('submit', function(e) {
  e.preventDefault();
  const type = document.getElementById('genType');
  const format = document.getElementById('genFormat');
  const typeLabels = { procurement:'Purchase Request Report', suppliers:'Supplier Directory', orders:'Procurement Summary', bids:'Bid Analysis Report', custom:'Custom Report' };
  
  if (format.value === 'pdf') {
     alert(`Generating and downloading "${typeLabels[type.value]}" in ${format.value.toUpperCase()} format...`);
     window.location.href = `{{ route('pmo.reports.download') }}?type=${encodeURIComponent(type.value)}`;
  } else {
     alert(`Generating and downloading "${typeLabels[type.value]}" in ${format.value.toUpperCase()} format... (Simulation)`);
  }
  
  bootstrap.Modal.getInstance(document.getElementById('generateReportModal')).hide();
  this.reset();
});
</script>
@endsection
