<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $title }}</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #009639; padding-bottom: 10px; }
        .header img { height: 60px; width: auto; vertical-align: middle; margin-right: 10px; }
        .header h1 { margin: 0; color: #009639; font-size: 18px; line-height: 1.2; }
        .header p { margin: 0; color: #666; font-size: 11px; }
        
        .meta { margin-bottom: 20px; font-size: 11px; color: #555; overflow: hidden; }
        .meta-left { float: left; }
        .meta-right { float: right; text-align: right; }

        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 6px; text-align: left; font-size: 11px; }
        th { background-color: #f2f2f2; font-weight: bold; color: #333; }
        tr:nth-child(even) { background-color: #fafafa; }

        .footer { position: fixed; bottom: 0; left: 0; right: 0; font-size: 10px; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 5px; }
    </style>
</head>
<body>
    <div class="header">
        <img src="{{ public_path('images/CLSU_LOGO.png') }}" alt="CLSU Logo">
        <h1>{{ $title }}</h1>
        <p>Central Luzon State University - Admin Panel</p>
    </div>

    <div class="meta">
        <div class="meta-left">
            <strong>Generated By:</strong> {{ Auth::user()->name ?? 'System Admin' }}
        </div>
        <div class="meta-right">
            <strong>Date:</strong> {{ now()->format('F d, Y h:i A') }}
        </div>
    </div>

    @if($type === 'offices')
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Code</th>
                    <th>Acronym</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $item)
                <tr>
                    <td>{{ $item->name }}</td>
                    <td>{{ $item->code }}</td>
                    <td>{{ $item->acronym }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @elseif($type === 'services')
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Office</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $item)
                <tr>
                    <td>{{ $item->name }}</td>
                    <td>{{ $item->office->name ?? 'N/A' }}</td>
                    <td>{{ $item->is_active ? 'Active' : 'Inactive' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @elseif($type === 'programs')
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Office</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $item)
                <tr>
                    <td>{{ $item->name }}</td>
                    <td>{{ $item->office->name ?? 'N/A' }}</td>
                    <td>{{ $item->is_active ? 'Active' : 'Inactive' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @elseif($type === 'news')
        <table>
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Office</th>
                    <th>Published At</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $item)
                <tr>
                    <td>{{ $item->title }}</td>
                    <td>{{ $item->office->name ?? 'N/A' }}</td>
                    <td>{{ $item->published_at ? $item->published_at->format('M d, Y') : 'Draft' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @elseif($type === 'inquiries')
        <table>
            <thead>
                <tr>
                    <th>Subject</th>
                    <th>Sender</th>
                    <th>Email</th>
                    <th>Date</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $item)
                <tr>
                    <td>{{ $item->subject }}</td>
                    <td>{{ $item->name }}</td>
                    <td>{{ $item->email }}</td>
                    <td>{{ $item->created_at->format('M d, Y') }}</td>
                    <td>{{ ucfirst($item->status) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @elseif($type === 'users')
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Office</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $item)
                <tr>
                    <td>{{ $item->last_name }}, {{ $item->first_name }}</td>
                    <td>{{ $item->email }}</td>
                    <td>{{ $item->office->name ?? 'N/A' }}</td>
                    <td>{{ ucfirst($item->status) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div style="text-align: center; padding: 50px; color: #777;">
            <p>No data template available for this report type.</p>
        </div>
    @endif

    <div class="footer">
        Generated via CLSU Admin System | Page <span class="page-number"></span>
    </div>

    <script type="text/php">
        if (isset($pdf)) {
            $pdf->page_script('
                $font = $fontMetrics->get_font("sans-serif", "normal");
                $pdf->text(520, 820, "Page " . $PAGE_NUM . " of " . $PAGE_COUNT, $font, 9);
            ');
        }
    </script>
</body>
</html>
