<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Archive Summary Report - CLSU RMO</title>
    <style>
        body { font-family: sans-serif; margin: 20px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #009639; padding-bottom: 10px; }
        .header h1 { margin: 0; color: #009639; font-size: 1.4em; }
        .header p { margin: 5px 0; color: #666; }
        .logo-container { text-align: center; margin-bottom: 10px; }
        .logo-container img { height: 80px; width: auto; }

        .meta-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 0.9em; border: none; }
        .meta-table td { border: none; padding: 5px 0; }
        .text-right { text-align: right; }

        .summary-box { background: #e6f6ec; border: 1px solid #b3e0c7; border-radius: 4px; padding: 12px; margin-bottom: 20px; }
        .summary-box h3 { margin: 0 0 8px 0; color: #009639; font-size: 1em; }

        table.data-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 0.8em; }
        table.data-table th, table.data-table td { border: 1px solid #ddd; padding: 6px 8px; text-align: left; }
        table.data-table th { background-color: #e6f6ec; color: #009639; }

        .footer { margin-top: 30px; font-size: 0.8em; text-align: center; color: #777; border-top: 1px solid #eee; padding-top: 10px; }
        .text-center { text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo-container">
            <img src="{{ public_path('images/CLSU_LOGO.png') }}" class="logo-image">
        </div>
        <h1>Archive Summary Report</h1>
        <p>Records Management Office</p>
        <p>Central Luzon State University</p>
    </div>

    <table class="meta-table">
        <tr>
            <td><strong>Generated By:</strong> {{ Auth::guard('admin')->user()->name ?? 'System Admin' }}</td>
            <td class="text-right"><strong>Date:</strong> {{ now()->format('F d, Y h:i A') }}</td>
        </tr>
        @if($dateFrom && $dateTo)
        <tr>
            <td colspan="2"><strong>Reporting Period:</strong> {{ \Carbon\Carbon::parse($dateFrom)->format('M d, Y') }} - {{ \Carbon\Carbon::parse($dateTo)->format('M d, Y') }}</td>
        </tr>
        @endif
    </table>

    <div class="summary-box">
        <h3>Archive Summary</h3>
        <p style="font-size: 0.85em; margin: 0;">
            <strong>Total Archived:</strong> {{ $data->count() }}
            @foreach($categoryCounts as $cat => $count)
                &nbsp;&nbsp;|&nbsp;&nbsp; <strong>{{ ucfirst($cat) }}:</strong> {{ $count }}
            @endforeach
        </p>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                <th style="width:5%">#</th>
                <th style="width:15%">Reference No</th>
                <th style="width:25%">Document Name</th>
                <th style="width:15%">Category</th>
                <th style="width:13%">File Size</th>
                <th style="width:15%">Date Created</th>
                <th style="width:15%">Date Archived</th>
            </tr>
        </thead>
        <tbody>
            @forelse($data as $index => $doc)
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td>{{ $doc->reference_no }}</td>
                <td>
                    <strong>{{ $doc->name }}</strong>
                    @if($doc->description)
                    <br><small>{{ Str::limit($doc->description, 40) }}</small>
                    @endif
                </td>
                <td>{{ ucfirst($doc->category ?? 'N/A') }}</td>
                <td>{{ $doc->file_size ? number_format($doc->file_size / 1024, 1) . ' KB' : 'N/A' }}</td>
                <td>{{ $doc->created_at->format('M d, Y') }}</td>
                <td>{{ $doc->archived_at ? $doc->archived_at->format('M d, Y') : 'N/A' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="7" class="text-center">No archived documents found for the selected criteria.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated via CLSU Records Management Office System &bull; {{ now()->format('Y') }}
    </div>
</body>
</html>
