<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stock Level Dashboard Report - CLSU PSO</title>
    <style>
        body { font-family: sans-serif; margin: 20px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #004d40; padding-bottom: 10px; }
        .header h1 { margin: 0; color: #004d40; }
        
        .logo-container { text-align: center; margin-bottom: 15px; }
        .logo-container img { height: 80px; width: auto; }
        
        .meta-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 0.9em; border: none; }
        .meta-table td { border: none; padding: 5px 0; }
        .text-right { text-align: right; }

        .section-title { border-bottom: 1px solid #eee; padding-bottom: 5px; margin-bottom: 15px; color: #004d40; }
        
        .stats-table { width: 100%; border-collapse: separate; border-spacing: 10px; margin-bottom: 30px; }
        .stat-card { border: 1px solid #ddd; padding: 15px; border-radius: 5px; text-align: center; background: #fff; }
        .stat-value { font-size: 2em; font-weight: bold; color: #004d40; display: block; margin-bottom: 5px; }
        .stat-label { color: #666; font-size: 0.9em; display: block; }
        
        table.data-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 0.85em; }
        table.data-table th, table.data-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        table.data-table th { background-color: #f2f2f2; }
        
        .footer { margin-top: 30px; font-size: 0.8em; text-align: center; color: #777; border-top: 1px solid #eee; padding-top: 10px; }
    </style>
</head>
<body>
    @php
        $path = public_path('images/CLSU_LOGO.png');
        $type = pathinfo($path, PATHINFO_EXTENSION);
        $logoData = file_get_contents($path);
        $base64 = 'data:image/' . $type . ';base64,' . base64_encode($logoData);
    @endphp

    <div class="header">
        <div class="logo-container">
            <img src="{{ $base64 }}" alt="CLSU Logo">
        </div>
        <h1>Stock Level Dashboard Report</h1>
        <p>Property and Supply Office</p>
        <p>Central Luzon State University</p>
    </div>

    <table class="meta-table">
        <tr>
            <td><strong>Generated By:</strong> {{ Auth::guard('admin')->user()->name ?? 'System Admin' }}</td>
            <td class="text-right"><strong>Date:</strong> {{ now()->format('F d, Y h:i A') }}</td>
        </tr>
    </table>

    <h3 class="section-title">Inventory Overview</h3>
    
    <table class="stats-table">
        <tr>
            <td class="stat-card" width="25%">
                <span class="stat-value">{{ $stats['total_plans'] }}</span>
                <span class="stat-label">Total Supply Records</span>
            </td>
            <td class="stat-card" width="25%">
                <span class="stat-value">{{ $stats['active_plans'] }}</span>
                <span class="stat-label">Active Supplies</span>
            </td>
            <td class="stat-card" width="25%">
                <span class="stat-value">{{ $stats['total_projects'] }}</span>
                <span class="stat-label">Total Properties</span>
            </td>
            <td class="stat-card" width="25%">
                <span class="stat-value">{{ $stats['completed_projects'] }}</span>
                <span class="stat-label">Issued Properties</span>
            </td>
        </tr>
    </table>

    <h3 class="section-title">Property Status Breakdown</h3>
    <table class="data-table">
        <thead>
            <tr>
                <th>Status</th>
                <th>Count</th>
                <th>Percentage</th>
            </tr>
        </thead>
        <tbody>
            @foreach($stats['project_status_counts'] as $status => $count)
            <tr>
                <td>{{ $status }}</td>
                <td>{{ $count }}</td>
                <td>{{ $stats['total_projects'] > 0 ? round(($count / $stats['total_projects']) * 100, 1) : 0 }}%</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated via CLSU Property & Supply System
    </div>
</body>
</html>
