<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Supply Issuance Report - CLSU PSO</title>
    <style>
        body { font-family: sans-serif; margin: 20px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #004d40; padding-bottom: 10px; }
        .header h1 { margin: 0; color: #004d40; }
        .header p { margin: 5px 0; color: #666; }
        .logo-container { text-align: center; margin-bottom: 15px; }
        .logo-container img { height: 80px; width: auto; }
        
        .meta-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 0.9em; border: none; }
        .meta-table td { border: none; padding: 5px 0; }
        .text-right { text-align: right; }

        table.data-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 0.85em; }
        table.data-table th, table.data-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        table.data-table th { background-color: #f2f2f2; color: #004d40; }
        .status-active { color: green; font-weight: bold; }
        .status-completed { color: blue; font-weight: bold; }
        .status-on_hold { color: orange; font-weight: bold; }
        .status-cancelled { color: red; font-weight: bold; }
        .footer { margin-top: 30px; font-size: 0.8em; text-align: center; color: #777; border-top: 1px solid #eee; padding-top: 10px; }
    </style>
</head>
<body>
    @php
        $path = public_path('images/CLSU_LOGO.png');
        $type = pathinfo($path, PATHINFO_EXTENSION);
        $logoData = file_get_contents($path);
        $base64 = 'data:image/' . $type . ';base64,' . base64_encode($logoData);
    @endphp

    <div class="header">
        <div class="logo-container">
            <img src="{{ $base64 }}" alt="CLSU Logo">
        </div>
        <h1>Supply Issuance Report</h1>
        <p>Property and Supply Office</p>
        <p>Central Luzon State University</p>
    </div>

    <table class="meta-table">
        <tr>
            <td><strong>Generated By:</strong> {{ Auth::guard('admin')->user()->name ?? 'System Admin' }}</td>
            <td class="text-right"><strong>Date:</strong> {{ now()->format('F d, Y h:i A') }}</td>
        </tr>
        @if(isset($date_from) && isset($date_to))
        <tr>
            <td colspan="2"><strong>Reporting Period:</strong> {{ \Carbon\Carbon::parse($date_from)->format('M d, Y') }} - {{ \Carbon\Carbon::parse($date_to)->format('M d, Y') }}</td>
        </tr>
        @endif
    </table>

    <table class="data-table">
        <thead>
            <tr>
                <th>Code</th>
                <th>Property Name</th>
                <th>Category</th>
                <th>Value</th>
                <th>Timeline</th>
                <th>Status</th>
                <th>Progress</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $project)
            <tr>
                <td>{{ $project->project_code }}</td>
                <td>
                    <strong>{{ $project->name }}</strong><br>
                    <small>{{ Str::limit($project->description, 50) }}</small>
                </td>
                <td>{{ $project->category }}</td>
                <td>₱{{ number_format($project->budget, 2) }}</td>
                <td>{{ $project->start_date->format('M Y') }} - {{ $project->end_date->format('M Y') }}</td>
                <td class="status-{{ $project->status }}">{{ ucfirst(str_replace('_', ' ', $project->status)) }}</td>
                <td>{{ $project->progress }}%</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated via CLSU Property & Supply System
    </div>
</body>
</html>
