<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $title }}</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #009639; padding-bottom: 10px; }
        .header img { height: 70px; width: auto; margin-bottom: 10px; }
        .header h1 { margin: 0; color: #009639; font-size: 20px; text-transform: uppercase; }
        .header p { margin: 5px 0 0; color: #666; font-size: 11px; }
        
        .meta-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 11px; }
        .meta-table td { padding: 5px; }
        .text-right { text-align: right; }
        
        .summary-box { background-color: #f8f9fa; border: 1px solid #ddd; padding: 15px; margin-bottom: 20px; border-radius: 4px; }
        .summary-title { font-weight: bold; color: #009639; margin-bottom: 10px; font-size: 14px; }
        
        table.data-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        table.data-table th, table.data-table td { border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 11px; }
        table.data-table th { background-color: #009639; color: white; font-weight: bold; }
        table.data-table tr:nth-child(even) { background-color: #f2f2f2; }
        
        .footer { position: fixed; bottom: 0; left: 0; right: 0; font-size: 10px; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 10px; }
        
        .badge { padding: 2px 6px; border-radius: 3px; font-size: 10px; font-weight: bold; color: white; }
        .bg-active { background-color: #28a745; }
        .bg-inactive { background-color: #6c757d; }
        .bg-leave { background-color: #fd7e14; }
        .bg-retired { background-color: #17a2b8; }
    </style>
</head>
<body>
    <div class="header">
        <img src="{{ public_path('images/CLSU_LOGO.png') }}" alt="CLSU Logo">
        <h1>{{ $title }}</h1>
        <p>Human Resources Management Office | Central Luzon State University</p>
    </div>

    <table class="meta-table">
        <tr>
            <td><strong>Generated By:</strong> {{ Auth::guard('admin')->user()->name ?? 'System Admin' }}</td>
            <td class="text-right"><strong>Date:</strong> {{ now()->format('F d, Y h:i A') }}</td>
        </tr>
        @if(isset($dateFrom) && isset($dateTo))
        <tr>
            <td colspan="2"><strong>Reporting Period:</strong> {{ \Carbon\Carbon::parse($dateFrom)->format('M d, Y') }} - {{ \Carbon\Carbon::parse($dateTo)->format('M d, Y') }}</td>
        </tr>
        @endif
    </table>

    @if($reportType === 'Employee List')
        <div class="summary-box">
            <span class="summary-title">Executive Summary</span>
            <p style="margin: 5px 0 0; font-size: 11px;">
                Total Records: <strong>{{ $data->count() }}</strong>
                @if(isset($filters) && count($filters) > 0)
                    | Filters Applied: {{ implode(', ', $filters) }}
                @endif
            </p>
        </div>

        <table class="data-table">
            <thead>
                <tr>
                    <th width="15%">Employee ID</th>
                    <th width="25%">Name</th>
                    <th width="20%">Position</th>
                    <th width="15%">Date Hired</th>
                    <th width="15%">Employment</th>
                    <th width="10%">Status</th>
                </tr>
            </thead>
            <tbody>
                @forelse($data as $employee)
                <tr>
                    <td>{{ $employee->employee_id }}</td>
                    <td>{{ $employee->last_name }}, {{ $employee->first_name }} {{ $employee->middle_name }}</td>
                    <td>{{ $employee->position ?? 'N/A' }}</td>
                    <td>{{ $employee->date_hired ? \Carbon\Carbon::parse($employee->date_hired)->format('M d, Y') : 'N/A' }}</td>
                    <td>{{ ucfirst(str_replace('_', ' ', $employee->employment_status)) }}</td>
                    <td>
                        <span class="badge bg-{{ $employee->status == 'on_leave' ? 'leave' : $employee->status }}">
                            {{ ucfirst(str_replace('_', ' ', $employee->status)) }}
                        </span>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="6" style="text-align: center;">No records found.</td>
                </tr>
                @endforelse
            </tbody>
        </table>

    @elseif($reportType === 'Status Summary' || $reportType === 'Employment Type Distribution' || $reportType === 'Department Overview')
        <table class="data-table">
            <thead>
                <tr>
                    <th width="70%">Category</th>
                    <th width="30%" style="text-align: right;">Count</th>
                </tr>
            </thead>
            <tbody>
                @php $total = 0; @endphp
                @foreach($data as $key => $count)
                <tr>
                    <td>{{ ucfirst(str_replace('_', ' ', $key)) }}</td>
                    <td style="text-align: right;">{{ $count }}</td>
                </tr>
                @php $total += $count; @endphp
                @endforeach
                <tr style="font-weight: bold; background-color: #e6f6ec;">
                    <td>TOTAL</td>
                    <td style="text-align: right;">{{ $total }}</td>
                </tr>
            </tbody>
        </table>
        
        <div style="margin-top: 20px; font-size: 11px; color: #666;">
            * Data reflects the current state of the system database as of generation time.
        </div>

    @else
        <p>Report data is not available for this type.</p>
    @endif

    <div class="footer">
        Generated via CLSU HRMO Management System &bull; {{ now()->format('Y') }}
    </div>
</body>
</html>
